export const FETCH_POSTS = 'COLLECTIONS/FETCH_POSTS'
export const REQUEST_FETCH_POSTS = 'COLLECTIONS/REQUEST_FETCH_POSTS'
export const IS_LOADING = 'IS_LOADING'

export const SET_MEAL_DATA = 'MEALS/SET_MEAL_DATA'
export const REQUEST_SET_MEAL_DATA = 'MEALS/REQUEST_SET_MEAL_DATA'
export const REMOVE_MEAL_ITEM = 'MEALS/REMOVE_MEAL_ITEM'

//Search
export const SET_SEARCH = 'SEARCH/SET_SEARCH'
export const REQUEST_SET_SEARCH = 'SEARCH/REQUEST_SET_SEARCH'
export const SET_SEARCH_RESULT = 'SEARCH/REQUEST_SET_SEARCH_RESULT'

//Detailed Post
export const REQUEST_DETAILED_POST = 'DETAILEDPOST/REQUEST_DETAILED_POST'
export const SET_DETAILED_POST = 'DETAILEDPOST/SET_DETAILED_POST'
export const SET_DETAILED_POST_ID = 'DETAILEDPOST/SET_DETAILED_POST_ID'